apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmsweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmsweb
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: cmsweb
    spec:
      containers:
      - name: adsfrontend
        image: vda/adtech_frontend
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cmsweb
  labels:
    app: cmsweb
spec:
  type: NodePort
  ports:
    - name: adsfrontend
      port: 3000
      targetPort: 3000
      nodePort: 30007
  selector:
    app: cmsweb